/**
 * @file Ficheiro que contém as funções relativas ao guião 1
 */

#ifndef GUIAO1_H_INCLUDED
#define GUIAO1_H_INCLUDED
#include "stack.h"


DADOS SOMAR_DADOS(DADOS x, DADOS y);

DADOS MULTIPLICAR_DADOS (DADOS x, DADOS y);

DADOS SUBTRAIR_DADOS (DADOS x, DADOS y);

DADOS DIVIDIR_DADOS (DADOS x, DADOS y);

DADOS INCREMENTAR_DADOS (DADOS x);

DADOS DECREMENTAR_DADOS (DADOS x);

DADOS MODULO_DADOS (DADOS x, DADOS y);

DADOS ELEVADO_DADOS (DADOS x, DADOS y);

DADOS CONJUNCAO_DADOS (DADOS x, DADOS y);

DADOS DISJUNCAO_DADOS (DADOS x, DADOS y);

DADOS XOR_DADOS(DADOS x, DADOS y);

DADOS NOT_DADOS (DADOS x);


#endif //MAIN_C_GUIAO1_H
